[core]
reloadable = true
order = 0

[package]
version = "1.3.1"
category = "Visualization"
title = "Foxglove Extension"
description = "Link your simulation to the Foxglove visualization platform"
authors = ["Robin Dumas @ Foxglove"]
repository = ""
keywords = ["Foxglove", "Data Visualization", "WebSocket"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}

[[python.module]]
name = "foxglove.tools.ws_bridge"

[python.pipapi]
use_online_index = true
requirements = ["foxglove-websocket==0.1.2", "foxglove-schemas-protobuf==0.2.1"]